server:
  port: 80
spring:
  message:
    basename: i18n/Messages,i18n/Pages
  jms:
    pub-sub-domain: false   # 配置消息的类型，true：topic消息，false：queue消息
  activemq:
    user: shenzk
    password: shenzk
    broker-url: tcp://127.0.0.1:61616
    packages:
      trust-all: true   # 当需要传输对象的时候必须开启，不然报错

mq:
  queue: shenzk.queue
  topic: shenzk.topic
  objQueue: shenzk.objQueue